<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<None Remove="avatar.png" />
		<None Remove="Images\avatar.png" />
		<None Remove="Images\logo.png" />
		<None Remove="logo.png" />
	</ItemGroup>
	
	<ItemGroup>
		<EmbeddedResource Include="Images\avatar.png" />
		<EmbeddedResource Include="Images\logo.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="logo.png" />
		<Resource Include="avatar.png" />
	</ItemGroup>

</Project>
